apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
  labels:
    app: springapp1
spec:
  nodeSelector: 
    kubernetes.io/hostname: controlplane
  imagePullSecrets:
    - name: docker-cred
  containers:
    - name: tomc
      image: polinux/stress 
      resources:
        requests:
          cpu: 700m
        
  volumes:
    - name: docker-secr
      secret:
        secretName: docker-cred
        items:
          - key: .dockerconfigjson
            path: config.json
