apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  containers:
    - name: dotfile-test-container
      image: heartocean/utils:live
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: basic-auth
  
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: basic-auth
