apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
  namespace: ts
data:
  .secret-file: dmFsdWUtMg0KDQo=
controlplane:~/k8s/manifests/ref_secrets$ cat 3_k8s_pod_secret_dotfile.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: heartocean/utils:live
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
