apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  initContainers:
    - name: pod1
      image: bitnami/kaniko
      args:
        - "--dockerfile=/store/Dockerfile"
        - "--context=/store/"
        - "destination=heartocean/docom:deletethis"
      volumeMounts:
        - name: sec-vol
          mountPath: /home/kaniko/.docker/
        - name: vol2
          mountPath: /store/

  volumes:
    - name: sec-vol
      secret:
        secretname: docker-cred     
          items:
            - key: .dockerconfigjson:
              path: config.json

    - name: vol2
      hostPath:
        path: /root/spring-boot-mongo-docker/
