apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  containers:
    - name: live
      image: heartocean/utils:live
      redinessProbe:
        exec:
          command: 
            - "ls"
            - "/etc/"
        initialDelaySeconds: 5
        periodSeconds: 5      
