apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app1
  namespace: ts
  labels:
    app: springapp1
spec:
  containers:
    - name: tomc
      image: heartocean/docom:spring1
      env:
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              name: cmap2 
              key: player_initial_lives
        - name: UI_PROPERTY_FILE_NAME
          valueFrom:
            configMapKeyRef: 
              name: cmap2
              key: ui_properties_file_name
       
      ports:
        - name: tomp
          containerPort: 8080

      volumeMounts:
        - name: cmap-vol1
          mountPath: /opt

  volumes:
    - name: cmap-vol1
      configMap:
        name: cmap2
        
        items:
          - key: "game.properties"
            path: "game.properties"
          
          - key: "user-interface.properties"
            path: "user-interface.properties"
