apiVersion: v1
kind: Secret
metadata:
  name: usr-pass1
data:
  .usr_pass: dXNlcm5hbWU6ICdoYWxvZ2VuJwpwYXNzd29yZDogJ2hhbG9nZW4xMjMnCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  imagePullSecrets:
    - name: docker-cred
  containers:
    - name: con1
      image: heartocean/pvt:alpine_live
      imagePullPolicy: IfNotPresent #Always,Never,IfNotPresent
      env: 
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name:  /opt/.user/
              key: username
            
        - name: PASSWD
          valueFrom:
            secretKeyRef:
              name: /opt/.user/
              key: password

      command: ["sh","echo $USERNAME && echo $PASSWD"]

      volumeMounts:
        - name: sec1
          mountPath: /opt/

  volumes:
    - name: sec1
      secret:
        secretName: usr-pass1
        items:
          - key: .usr_pass
            path: .user
