apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  nodeSelector:
    kubernetes.io/hostname: controlplane
  imagePullSecrets:
    - name: docker-cred
  containers:
    - name: con1
      image: heartocean/pvt:alpine_live_entrypoint
      imagePullPolicy: Always #Always,Never,IfNotPresent
      args: 
        - "499"
