apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  imagePullSecret:
    - name: docker-cred
  containers:
    - name: con1
      image: heartocean/pvt:alpine_live_entrypoint
      imagePullPolicy: IfNotPresent #Always,Never,IfNotPresent
      args: 
        - "499"
