apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  containers:
    - name: con1
      image: alpine
      imagePullPolicy: IfNotPresent #Always,Never,IfNotPresent
      command: ["sh","-c","sleep","300"] # NOTE: sh -c which expects a single string as the command to execute.
      
