apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  imagePullSecrets:
    - name: docker-cred
  initContainers:
    - name: kaniko
      image: bitnami/kaniko
      imagePullPolicy: IfNotPresent #Always,Never,IfNotPresent
      args:
        - "--dockerfile=/space/dockerfile_alpine_live"
        - "--context=/space/"
        - "--destination=heartocean/pvt:alpine_live"
      volumeMounts:
        - name: docker-cred
          mountPath: /kaniko/.docker/
        - name: dockerfile-vol
          mountPath: /space/ 
    - name: kaniko2
      image: bitnami/kaniko
      imagePullPolicy: IfNotPresent #Always,Never,IfNotPresent
      args:
        - "--dockerfile=/space/dockerfile_alpine_live_entryPoint"
        - "--context=/space/"
        - "--destination=heartocean/pvt:alpine_live_entrypoint"
      volumeMounts:
        - name: docker-cred
          mountPath: /kaniko/.docker/
        - name: dockerfile-vol
          mountPath: /space/

  containers:
    - name: con1
      image: heartocean/pvt:alpine_live
      imagePullPolicy: IfNotPresent #Always,Never,IfNotPresent
 
  volumes:
    - name: docker-cred
      secret:
        secretName: docker-cred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-vol
      hostPath:
        path: .
