apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
  labels:
    app: springapp1
spec:
  imagePullSecrets:
    - name: docker-cred
  initContainers:
    - name: kaniko
      image: bitnami/kaniko
      args: 
        - "--dockerfile=/space/multi_mvn_tom_settings" 
        - "--context=/space/"
        - "--destination=heartocean/pvt:spring1"
      volumeMounts:
        - name: dev-vol
          mountPath: /space
        - name: docker-secr
          mountPath: /kaniko
  containers:
    - name: tomc
      image: heartocean/pvt:spring1
      ports: 
        - containerPort: 8080
          name: tomp

  volumes:
    - name: dev-vol
      hostPath:
        path: /home/alpine/k8s/manifests/prj1/spring-boot-mongo-docker
        type: Directory
    - name: docker-secr
      secret:
        secretName: docker-cred
        items:
          - key: .dockerconfigjson
            path: config.json
