apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
spec:
  initContainers:
    - name: kaniko
      image: bitnami/kaniko
      args: 
        - "--dockerfile=/devcode/multi_mvn_tom_settings" 
        - "--context=/devcode/"
        - "--destination=heartocean/docom:deletethis"
      volumeMounts:
        - name: dev-vol
          mountPath: /devcode
        - name: docker-secr
          mountPath: /home/kaniko
  containers:
    - name: tomc
      image: heartocean/docom:deletethis
      ports: 
        - containerPort: 8080
          name: tomp
  
  volumes:
    - name: dev-vol
      hostPath:
        path: /home/alpine/k8s/manifests/prj1/spring-boot-mongo-docker
        type: Directory
    - name: docker-secr
      secret:
        secretName: docker-cred
        items:
          - key: .dockerconfigjson
            path: config.json
