apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
  labels:
    app: springapp1
spec:
  nodeSelector: 
    kubernetes.io/hostname=controlplane
  imagePullSecrets:
    - name: docker-cred
  initContainers:
    - name: kaniko
      image: bitnami/kaniko
      args: 
        - "--dockerfile=/space/app/multi_mvn_tom_settings" 
        - "--context=/space/app"
        - "--destination=heartocean/pvt:spring1"
      volumeMounts:
        - name: vol1
          mountPath: /space/app
        - name: docker-secr
          mountPath: /kaniko
  containers:
    - name: tomc
      image: heartocean/pvt:spring1
      ports: 
        - containerPort: 8080
          name: tomp

  volumes:
    - name: vol1
      hostPath:
        path: /root/spring-boot-mongo-docker
        type: Directory
    - name: docker-secr
      secret:
        secretName: docker-cred
        items:
          - key: .dockerconfigjson
            path: config.json
